language: node_js
node_js: "12.10.0"

cache:
  npm: false

os:
  - osx

install:
  - npm install

script:
  - npm run dist -- -mwl

deploy:
  provider: releases
  token: $GH_TOKEN
  file:
    - release/*.exe
    - release/*.dmg
    - release/*.deb
  skip_cleanup: true
  on:
    tags: true

