language: node_js
node_js: "12.10.0"

cache:
  npm: false

env:
  global:
    - DEBUG=off
    - NODE_ENV=production

os:
  - osx

before_install:
  - npm i -g npx
  - npm i -g webpack-cli@3.1.0

install:
  - npm install

script:
  - npm test
  - npm run dist -- -mwl

deploy:
  provider: releases
  token: $GITHUB_PERSONAL_TOKEN
  file:
    - release/*.exe
    - release/*.dmg
    - release/*.deb
  cleanup: false
  on:
    tags: true

